// @generated by `ruskel-snapshot`; do not edit.
//
// Package: snips
// Publish: crates.io
// Binaries: snips
// Workspace dependencies: none
// Workspace dependents: none

//! Snips keeps markdown snippets synchronized with their source files.

use std::{
    fmt::{Debug, Display},
    path::{Path, PathBuf},
};

/// Policy for handling command-based snippet markers.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum CommandPolicy {
    /// Prompt for confirmation before running each command.
    Prompt,
    /// Allow command execution without prompting.
    Allow,
    /// Disallow command execution entirely.
    Deny,
}

/// Result of rendering snippets within a single markdown file.
#[derive(Debug)]
pub struct RenderSummary {
    /// Whether the file content changed during rendering.
    pub updated: bool,
    /// The rendered content when `updated` is `true`.
    pub rendered: Option<String>,
    /// Snippet references found while processing the file.
    pub snippets: Vec<SnippetReport>,
}

/// A difference between existing markdown content and the current snippet
/// content.
#[derive(Debug)]
pub struct SnippetDiff {
    /// Snippet marker source.
    pub locator: SnippetLocator,
    /// Content currently present in the markdown file.
    pub old_content: String,
    /// Fresh content produced by the snippet source.
    pub new_content: String,
}

/// A snippet reference captured from a markdown file.
#[derive(Clone, Debug, Eq, PartialEq)]
pub enum SnippetLocator {
    /// File-based snippet reference.
    File {
        /// Snippet source path relative to the markdown file.
        path: PathBuf,
        /// Optional snippet name inside the source file.
        name: Option<String>,
    },
    /// Command-based snippet reference.
    Command {
        /// Command to execute.
        command: String,
    },
}

impl SnippetLocator {
    /// Render the locator in marker form (e.g., `path/to/file#name` or
    /// `!command`).
    pub fn marker(&self) -> String;
}

/// Per-snippet report for a rendered markdown file.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct SnippetReport {
    /// Snippet location details.
    pub locator: SnippetLocator,
    /// Whether this snippet's content changed during render.
    pub updated: bool,
}

/// Errors produced while processing snippets.
#[derive(Debug, Display, std::error::Error)]
pub enum SnipsError {
    /// Referenced source file could not be read from disk.
    #[error("file not found: {file}")]
    FileNotFound {
        /// File that could not be read.
        file: PathBuf,
        /// Underlying OS error for additional context.
        #[source]
        source: std::io::Error,
    },
    /// Reading a file failed for reasons other than missing file.
    #[error("failed to read {file}: {source}")]
    FileReadFailed {
        /// File that could not be read.
        file: PathBuf,
        /// Underlying OS error.
        #[source]
        source: std::io::Error,
    },
    /// A marker was not followed by a fenced code block.
    #[error("marker not followed by code fence: line {0}")]
    MissingCodeFence(usize),
    /// A code fence was opened but never closed.
    #[error("code fence starting at line {start_line} in {file} is missing its closing fence")]
    UnterminatedCodeFence {
        /// Markdown file containing the unterminated fence.
        file: PathBuf,
        /// One-based line number where the fence opens.
        start_line: usize,
    },
    /// A marker does not match the expected syntax.
    #[error(
        "invalid marker format in {file}:{line}\n  {content}\n  Expected format: <!-- snips: path/to/file.ext -->, <!-- snips: path/to/file.ext#snippet_name -->, or <!-- snips: !command -->"
    )]
    InvalidMarker {
        /// Markdown file containing the invalid marker.
        file: PathBuf,
        /// One-based line number of the marker.
        line: usize,
        /// Full text of the offending line.
        content: String,
    },
    /// A requested snippet name is missing from the source file.
    #[error(
        "snippet `{snippet_name}` not found in {file}\nAvailable snippets: {available_snippets}"
    )]
    SnippetNotFound {
        /// Source file that was scanned for the snippet.
        file: PathBuf,
        /// Name of the missing snippet.
        snippet_name: String,
        /// Comma-separated list of snippets that were found.
        available_snippets: String,
    },
    /// A snippet start marker was found without a matching end marker.
    #[error("unterminated snippet `{1}` in {0}")]
    UnterminatedSnippet(PathBuf, String),
    /// Command execution was disabled by policy.
    #[error("command execution disabled: {command}")]
    CommandExecutionDisabled {
        /// Command that was blocked.
        command: String,
    },
    /// Command execution was denied by the user.
    #[error("command execution denied: {command}")]
    CommandExecutionDenied {
        /// Command that was denied.
        command: String,
    },
    /// Prompting for command execution was not possible.
    #[error("command execution requires confirmation but stdin is not interactive: {command}")]
    CommandConfirmationUnavailable {
        /// Command awaiting confirmation.
        command: String,
    },
    /// Spawning a command failed.
    #[error("failed to execute command `{command}`: {source}")]
    CommandSpawnFailed {
        /// Command that failed to start.
        command: String,
        /// Underlying IO error.
        #[source]
        source: std::io::Error,
    },
    /// Command returned a non-zero exit status.
    #[error("command `{command}` failed with status {status}: {stderr}")]
    CommandFailed {
        /// Command that returned non-zero.
        command: String,
        /// Exit status description.
        status: String,
        /// Captured stderr output (may be empty).
        stderr: String,
    },
    /// No markdown files were found in the working directory.
    #[error("no markdown files found in {0}")]
    NoMarkdownFiles(PathBuf),
    /// Any other I/O error propagated from the filesystem.
    #[error("IO error: {0}")]
    Io(std::io::Error),
}

impl From<std::io::Error> for SnipsError {}

/// Compute diffs between snippets embedded in `path` and their sources.
pub fn diff_file(
    path: &Path,
    command_policy: CommandPolicy,
) -> Result<Vec<SnippetDiff>, SnipsError>;

/// Process a single markdown file and optionally write updates in place.
pub fn sync_snippets_in_file(
    path: &Path,
    write: bool,
    command_policy: CommandPolicy,
) -> Result<Option<String>, SnipsError>;

/// Process a single markdown file, returning snippet metadata alongside
/// changes.
pub fn sync_snippets_in_file_with_summary(
    path: &Path,
    write: bool,
    command_policy: CommandPolicy,
) -> Result<RenderSummary, SnipsError>;

pub mod error {
    //! Error definitions used across the crate.

    pub use crate::SnipsError;
}

pub mod processor {
    //! Core processing logic for scanning and updating markdown files.

    pub use crate::{
        CommandPolicy, RenderSummary, SnippetDiff, SnippetLocator, SnippetReport, diff_file,
        sync_snippets_in_file, sync_snippets_in_file_with_summary,
    };
}

pub mod snippet {
    //! Helpers for locating and extracting snippets from source files.
}
